### ISSUE TITLE
Different order of sensordatavalues can lead to problems

### ISSUE THREAD

**Issue by dirkschumacher** [juliuste/berlinFeinstaub-bot#2]
If the sensordatavalues array is ordered differently the bot reports a wrong value:
https://github.com/juliuste/berlinFeinstaub-bot/blob/master/index.js#L29
```
{"sensordatavalues":[{"id":284314117,"value":"3.70","value_type":"P2"}, {"id":284314116,"value":"7.16","value_type":"P1"}]}
```

If this was the answer then the PM2.5 values would be used instead of PM10. Maybe there is a convention but I guess it would be better to select the value of `value_type` *P1*

**Comment by juliuste** [comment]
Feel free to create an issue [here](https://github.com/sbamueller/FeinstaubMelder/blob/master/tweetbeialarm.py#L25) as well (: (That's where I got the idea)
